Project2/force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>QuestionNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/A_Picked__c.field-meta.xml
<CustomField>
    <fullName>A_Picked__c</fullName>
    <label>A Picked</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/B_Picked__c.field-meta.xml
<CustomField>
    <fullName>B_Picked__c</fullName>
    <defaultValue>0</defaultValue>
    <label>B Picked</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/C_Picked__c.field-meta.xml
<CustomField>
    <fullName>C_Picked__c</fullName>
    <defaultValue>0</defaultValue>
    <label>C Picked</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/D_Picked__c.field-meta.xml
<CustomField>
    <fullName>D_Picked__c</fullName>
    <defaultValue>0</defaultValue>
    <label>D Picked</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Passing__c.field-meta.xml
<CustomField>
    <fullName>Passing__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Passing</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

project2/force-app/main/default/objects/Question__c/fields/Quiz__c.field-meta.xml
<CustomField>
    <fullName>Quiz__c</fullName>
    <label>Quiz</label>
    <referenceTo>Quiz__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project2/force-app/main/default/objects/Quiz__c/Quiz__c.object-meta.xml
<CustomObject>
    <label>Quiz</label>
    <nameField>
        <label>Quiz Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quizes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/TestAnswerPicked.cls
@isTest
public class TestAnswerPicked {

    @TestSetup
    public static void makeData(){
        
        MockDataProj2.dataInputQuizQuest();
        MockDataProj2.dataInputPlayerTeam();
        MockDataProj2.dataInputAttempAns();
        

        
    }
    
    @isTest
    public static void TestUpdateQuestionA() {


        Test.startTest();
        AnswerPickedTriggerHandler.updateQuestion();
        Test.stopTest();

        Quiz__c quiz = [SELECT id,Name FROM Quiz__c WHERE Name = 'Math 101' LIMIT 1];

        List<Question__c> questionListA = [SELECT Id, A_Picked__c, B_Picked__c,C_Picked__c, D_Picked__c, Passing__c FROM Question__c WHERE  Quiz__c=: quiz.Id];
       
        System.assertEquals(100, questionListA[0].A_Picked__c);

    }

    @isTest
    public static void TestUpdateQuestionC() {

        
        Test.startTest();
        AnswerPickedTriggerHandler.updateQuestion();
        Test.stopTest();

        Quiz__c quiz = [SELECT id,Name FROM Quiz__c WHERE Name = 'Math 101' LIMIT 1];

        List<Question__c> questionListA = [SELECT Id, A_Picked__c, B_Picked__c,C_Picked__c, D_Picked__c, Passing__c FROM Question__c WHERE  Quiz__c=: quiz.Id];

        System.assertEquals(0, questionListA[0].C_Picked__c);

    }    
    
    @isTest
    public static void TestUpdateQuestionB() {
        
        
        Test.startTest();
        AnswerPickedTriggerHandler.updateQuestion();
        Test.stopTest();

             Quiz__c quiz = [SELECT id,Name FROM Quiz__c WHERE Name = 'Math 101' LIMIT 1];

        List<Question__c> questionListA = [SELECT Id, A_Picked__c, B_Picked__c,C_Picked__c, D_Picked__c, Passing__c FROM Question__c WHERE  Quiz__c=: quiz.Id];

        System.assertEquals(0, questionListA[0].B_Picked__c);

    }    
    
    @isTest
    public static void TestUpdateQuestionD() {

       
        Test.startTest();
        AnswerPickedTriggerHandler.updateQuestion();
        Test.stopTest();

         Quiz__c quiz = [SELECT id,Name FROM Quiz__c WHERE Name = 'Math 101' LIMIT 1];

        List<Question__c> questionListA = [SELECT Id, A_Picked__c, B_Picked__c,C_Picked__c, D_Picked__c, Passing__c FROM Question__c WHERE  Quiz__c=: quiz.Id];

        System.assertEquals(0, questionListA[0].D_Picked__c);

    }    
}