force-app/main/default/objects/Attempt__c/Attempt__c.object-meta.xml
<CustomObject>
    <label>Attempt</label>
    <nameField>
        <displayFormat>AT-{0000}</displayFormat>
        <label>Attempt</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attempts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Attempt__c/fields/Player__c.field-meta.xml
<CustomField>
    <fullName>Player__c</fullName>
    <label>Player</label>
    <referenceTo>Player__c</referenceTo>
    <relationshipLabel>Attempts</relationshipLabel>
    <relationshipName>Attempts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project2/force-app/main/default/objects/Attempt__c/fields/Quiz__c.field-meta.xml
<CustomField>
    <fullName>Quiz__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quiz</label>
    <referenceTo>Quiz__c</referenceTo>
    <relationshipLabel>Attempts</relationshipLabel>
    <relationshipName>Attempts</relationshipName>
    <type>Lookup</type>
</CustomField>

Project2/force-app/main/default/objects/Player__c/Player__c.object-meta.xml
<CustomObject>
    <label>Player</label>
    <nameField>
        <label>Player Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Project2/force-app/main/default/objects/Player__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Players</relationshipName>
    <type>Lookup</type>
</CustomField>

Project2/force-app/main/default/objects/Quiz__c/Quiz__c.object-meta.xml
<CustomObject>
    <label>Quiz</label>
    <nameField>
        <label>Quiz Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quizes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Project2/force-app/main/default/classes/ChooseQuiz.cls
public with sharing class ChooseQuiz {
    public Attempt__c NewAttempt { get; set; }
    public Player__c player {get;set;}
    public ChooseQuiz(){
        player=getplayer();
        Id id = ApexPages.currentPage().getParameters().get('id');
        NewAttempt = (id == null) ? new Attempt__c() :
            [SELECT Name, Player__c, Quiz__c FROM Attempt__c WHERE Id = :id];
		
    }
       
    public Player__c getplayer() {
   		Player__c p=[SELECT Id, Name, User__c FROM PLayer__c WHERE User__c = :UserInfo.getUserID()];
        return p;
    }
    
    public pagereference SaveAttempt(){
        NewAttempt.Player__c = player.Id;
        insert NewAttempt;
        PageReference Page = new PageReference('/apex/QuizPage2');
    	Page.setRedirect(true);
    	return Page;
    }
    
}

//Old
/*
public class ChooseQuiz {
    apexpages.StandardController stdController;
    public ChooseQuiz(ApexPages.StandardController stdController){
        this.stdController = stdController;
    }
    
    public pagereference SaveAttempt(){
        stdController.save();
        PageReference Page = new PageReference('/apex/QuizPage');
    	Page.setRedirect(true);
    	return Page;
    }
    
}
*/