force-app/main/default/objects/Attempt__c/Attempt__c.object-meta.xml
<CustomObject>
    <label>Attempt</label>
    <nameField>
        <displayFormat>AT-{0000}</displayFormat>
        <label>Attempt</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attempts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Attempt__c/fields/Player__c.field-meta.xml
<CustomField>
    <fullName>Player__c</fullName>
    <label>Player</label>
    <referenceTo>Player__c</referenceTo>
    <relationshipLabel>Attempts</relationshipLabel>
    <relationshipName>Attempts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

project2/force-app/main/default/objects/Attempt__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <formula>Correct_Answers__c / Answers__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Project2/force-app/main/default/objects/Player__c/Player__c.object-meta.xml
<CustomObject>
    <label>Player</label>
    <nameField>
        <label>Player Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Player__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Player__c/fields/Quiz_Average__c.field-meta.xml
<CustomField>
    <fullName>Quiz_Average__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quiz Average</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Player__c/fields/Quiz_Taken__c.field-meta.xml
<CustomField>
    <fullName>Quiz_Taken__c</fullName>
    <label>Quiz Taken</label>
    <summaryForeignKey>Attempt__c.Player__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Project2/force-app/main/default/objects/Player__c/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <description>place holder for leaderboard rank</description>
    <label>Rank</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Player__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Players</relationshipLabel>
    <relationshipName>Players</relationshipName>
    <type>Lookup</type>
</CustomField>

Project2/force-app/main/default/objects/Player__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Players</relationshipName>
    <type>Lookup</type>
</CustomField>

project2/force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Project2/force-app/main/default/objects/Team__c/fields/Team_Rank__c.field-meta.xml
<CustomField>
    <fullName>Team_Rank__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Team Rank</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/Team_Score__c.field-meta.xml
<CustomField>
    <fullName>Team_Score__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Team Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LeaderBoardController.cls
public class LeaderBoardController {
    //list to obtain players
    public List<Player__c> players{get;set;}
    
       //constructor Querying players in database
    public LeaderBoardController() {
        players = [SELECT Name, Rank__c, Points__c, Team__r.Name FROM Player__c ORDER BY Rank__c ASC LIMIT 10];
        
    }
    
    // attempt list 
    public List<Attempt__c> attempt = new List<Attempt__c>();
    public List<Attempt__c> getattempt() {
   		List<Attempt__c> a=[SELECT id, Name, Score__c, Player__r.User__c
                            FROM Attempt__c 
                            WHERE Player__r.User__c =: UserInfo.getUserId() ORDER BY Name DESC LIMIT 5];
        return a;
    }
    
    //----- Personal stats ---
    public List<Player__c> player = new List<Player__c>();
    public List<Player__c> getplayer() {
   		List<Player__c> p=[SELECT Name, User__c, Team__c, Points__c, Rank__c, Quiz_Taken__c, Quiz_Average__c 
                           FROM PLayer__c WHERE User__c = :UserInfo.getUserID() ORDER BY Rank__c ASC];
        return p;
    }
    
    //-----Team leaderBoard ----
    public List<Team__c> team = new List<Team__c>();
    public list<Team__c> getteam(){
        	List<Team__c> t = [SELECT Name, Team_Rank__c, Team_Score__c FROM Team__c ORDER BY Team_Rank__c ASC];
        return t;
    }
    
  
         
  }