Project2/force-app/main/default/objects/Answer__c/Answer__c.object-meta.xml
<CustomObject>
    <label>Answer</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Answer</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Project2/force-app/main/default/objects/Answer__c/fields/Choice__c.field-meta.xml
<CustomField>
    <fullName>Choice__c</fullName>
    <label>Choice</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Answer__c/fields/IsCorrect__c.field-meta.xml
<CustomField>
    <fullName>IsCorrect__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsCorrect</label>
    <type>Checkbox</type>
</CustomField>

Project2/force-app/main/default/objects/Answer__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <formula>QuestionNumber__r.Question__c</formula>
    <label>Question</label>
    <type>Text</type>
</CustomField>

Project2/force-app/main/default/objects/Answer__c/fields/QuestionNumber__c.field-meta.xml
<CustomField>
    <fullName>QuestionNumber__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>QuestionNumber</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Answers</relationshipLabel>
    <relationshipName>Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

Project2/force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>QuestionNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/A_Picked__c.field-meta.xml
<CustomField>
    <fullName>A_Picked__c</fullName>
    <label>A Picked</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <label>Answer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question__c/fields/B_Picked__c.field-meta.xml
<CustomField>
    <fullName>B_Picked__c</fullName>
    <defaultValue>0</defaultValue>
    <label>B Picked</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/C_Picked__c.field-meta.xml
<CustomField>
    <fullName>C_Picked__c</fullName>
    <defaultValue>0</defaultValue>
    <label>C Picked</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/D_Picked__c.field-meta.xml
<CustomField>
    <fullName>D_Picked__c</fullName>
    <defaultValue>0</defaultValue>
    <label>D Picked</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Passing__c.field-meta.xml
<CustomField>
    <fullName>Passing__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Passing</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/AnswerPickedTriggerHandler.cls
public class AnswerPickedTriggerHandler {
    public static void updateQuestion(){
        List<Question__c> questionList = [SELECT Id, Name, A_Picked__c, B_Picked__c, C_Picked__c, D_Picked__c, Passing__c FROM Question__c];
        List<Answer__c> answerList = [SELECT Name, QuestionNumber__c, Choice__c, IsCorrect__c FROM Answer__c];
        for(Integer i = 0; i < questionList.Size(); i ++){
            Decimal Acount = 0, Bcount = 0, Ccount = 0, Dcount = 0, Total = 0, correct = 0, answers = 0;
            for(Answer__c a: answerList){
                if(a.QuestionNumber__c == questionList[i].Id){
                    if(a.IsCorrect__c == true)
                        correct++;
                    if(a.Choice__c == 'A')
                    	Acount++;
                    else if(a.Choice__c == 'B')
                    	Bcount++;
                    else if(a.Choice__c == 'C')
                    	Ccount++;
                    else if(a.Choice__c == 'D')
                    	Dcount++;
                    answers++;
                }
            }
            Total = Acount + Bcount + Ccount + Dcount;
            if(correct == 0)
                questionList[i].Passing__c = 0;
            else
            	questionList[i].Passing__c = (correct/answers)*100;
            If(Total == 0){
                questionList[i].A_Picked__c = 0;
                questionList[i].B_Picked__c = 0;
                questionList[i].C_Picked__c = 0;
                questionList[i].D_Picked__c = 0;
            }else{
            	questionList[i].A_Picked__c = (Acount/Total)*100;
                questionList[i].B_Picked__c = (Bcount/Total)*100;
                questionList[i].C_Picked__c = (Ccount/Total)*100;
                questionList[i].D_Picked__c = (Dcount/Total)*100;   
            }
        }
        update questionList;
    }
}