Project2/force-app/main/default/objects/Answer__c/Answer__c.object-meta.xml
<CustomObject>
    <label>Answer</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Answer</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Project2/force-app/main/default/objects/Answer__c/fields/A__c.field-meta.xml
<CustomField>
    <fullName>A__c</fullName>
    <formula>QuestionNumber__r.A__c</formula>
    <label>A</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Answer__c/fields/Attempt__c.field-meta.xml
<CustomField>
    <fullName>Attempt__c</fullName>
    <label>Attempt</label>
    <referenceTo>Attempt__c</referenceTo>
    <relationshipLabel>Answers</relationshipLabel>
    <relationshipName>Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project2/force-app/main/default/objects/Answer__c/fields/B__c.field-meta.xml
<CustomField>
    <fullName>B__c</fullName>
    <formula>QuestionNumber__r.B__c</formula>
    <label>B</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Answer__c/fields/C__c.field-meta.xml
<CustomField>
    <fullName>C__c</fullName>
    <formula>QuestionNumber__r.C__c</formula>
    <label>C</label>
    <type>Text</type>
</CustomField>

Project2/force-app/main/default/objects/Answer__c/fields/Choice__c.field-meta.xml
<CustomField>
    <fullName>Choice__c</fullName>
    <label>Choice</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project2/force-app/main/default/objects/Answer__c/fields/D__c.field-meta.xml
<CustomField>
    <fullName>D__c</fullName>
    <formula>QuestionNumber__r.D__c</formula>
    <label>D</label>
    <type>Text</type>
</CustomField>

Project2/force-app/main/default/objects/Answer__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <formula>QuestionNumber__r.Question__c</formula>
    <label>Question</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attempt__c/Attempt__c.object-meta.xml
<CustomObject>
    <label>Attempt</label>
    <nameField>
        <displayFormat>AT-{0000}</displayFormat>
        <label>Attempt</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attempts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Attempt__c/fields/Player__c.field-meta.xml
<CustomField>
    <fullName>Player__c</fullName>
    <label>Player</label>
    <referenceTo>Player__c</referenceTo>
    <relationshipLabel>Attempts</relationshipLabel>
    <relationshipName>Attempts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project2/force-app/main/default/objects/Player__c/Player__c.object-meta.xml
<CustomObject>
    <label>Player</label>
    <nameField>
        <label>Player Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Project2/force-app/main/default/objects/Player__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Players</relationshipName>
    <type>Lookup</type>
</CustomField>

Project2/force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>QuestionNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Project2/force-app/main/default/objects/Question__c/fields/A__c.field-meta.xml
<CustomField>
    <fullName>A__c</fullName>
    <label>A</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <label>Answer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question__c/fields/B__c.field-meta.xml
<CustomField>
    <fullName>B__c</fullName>
    <label>B</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/C__c.field-meta.xml
<CustomField>
    <fullName>C__c</fullName>
    <label>C</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Project2/force-app/main/default/objects/Question__c/fields/D__c.field-meta.xml
<CustomField>
    <fullName>D__c</fullName>
    <label>D</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QuizPage.cls
public with sharing class QuizPage {
    public list<Answer__c> questions {get;set;}
	public Integer rec { get; set; }
    public Integer tot { get; set; }
   	integer totalRecs = 0;
   	integer count= 0;
   	integer LimitSize= 1;
    
    List<Player__c> p=[SELECT Name, User__c FROM PLayer__c WHERE User__c = :UserInfo.getUserID()];
    public List<Attempt__c> attempt = [SELECT Id FROM Attempt__c WHERE Player__c =: p[0].Id ORDER BY LastModifiedDate DESC LIMIT 1];
    //public List<Answer__c> questions=new List<Answer__c>();
   	public List<Answer__c> getQuestions() {
   		List<Answer__c> q=[select Name, Question__c, A__c, B__c, C__c, D__c, Choice__c from Answer__c WHERE Attempt__c IN : attempt ORDER BY Name LIMIT:limitsize OFFSET:count];
        return q;
    }
    
    public QuizPage(){
    	tot=totalRecs = [select count() from Answer__c WHERE Attempt__c IN : attempt];
        //questions = [select Name, Question__c, A__c, B__c, C__c, D__c, Choice__c from Answer__c WHERE Attempt__c IN : attempt ORDER BY Name LIMIT:limitsize OFFSET:count];
        questions = getQuestions();
    }
        
    public void updatePage() {
        questions.clear();
        limitsize=rec;
        questions=[select Name, Question__c, A__c, B__c, C__c, D__c, Choice__c from Answer__c WHERE Attempt__c IN : attempt ORDER BY Name LIMIT:limitsize OFFSET:count];
    }
    
    public PageReference ChooseA() {
        for(Answer__c a: questions){
            a.Choice__c = 'A';
        }
        update questions;
        return null;
    }
    
    public PageReference ChooseB() {
        for(Answer__c a: questions){
            a.Choice__c = 'B';
        }
        update questions;
        return null;
    }
    
    public PageReference ChooseC() {
        for(Answer__c a: questions){
            a.Choice__c = 'C';
        }
        update questions;
        return null;
    }
    
    public PageReference ChooseD() {
        for(Answer__c a: questions){
            a.Choice__c = 'D';
        }
        update questions;
        return null;
    }
    
    public PageReference save() {
        try {
            update questions;
        } catch(system.DmlException e) {
            Apexpages.AddMessages(e);
            return null;
        }

        return null;
    }
    
    public PageReference prvbtn() {
    	count=count-limitsize;
        updatePage();
        return null;
    }

 	public PageReference Nxtbtn() {
 		count=count+limitsize;
        updatePage();
        return null;
    }
    
    public pagereference Submit(){
        PageReference Page = new PageReference('https://players-developer-edition.na136.force.com/s/');
    	Page.setRedirect(true);
    	return Page;
    }
 
    public Boolean getNxt() {
        if((count+ LimitSize) >= totalRecs)
       		return true;
     	else
       		return false;     
    }
    
    public Boolean getPrv() {
       if(count== 0)
           return true;
       else
           return false;
    }
}