Project2/force-app/main/default/objects/Answer__c/Answer__c.object-meta.xml
<CustomObject>
    <label>Answer</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Answer</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Project2/force-app/main/default/objects/Answer__c/fields/A__c.field-meta.xml
<CustomField>
    <fullName>A__c</fullName>
    <formula>QuestionNumber__r.A__c</formula>
    <label>A</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Answer__c/fields/Attempt__c.field-meta.xml
<CustomField>
    <fullName>Attempt__c</fullName>
    <label>Attempt</label>
    <referenceTo>Attempt__c</referenceTo>
    <relationshipLabel>Answers</relationshipLabel>
    <relationshipName>Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project2/force-app/main/default/objects/Answer__c/fields/B__c.field-meta.xml
<CustomField>
    <fullName>B__c</fullName>
    <formula>QuestionNumber__r.B__c</formula>
    <label>B</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Answer__c/fields/C__c.field-meta.xml
<CustomField>
    <fullName>C__c</fullName>
    <formula>QuestionNumber__r.C__c</formula>
    <label>C</label>
    <type>Text</type>
</CustomField>

Project2/force-app/main/default/objects/Answer__c/fields/D__c.field-meta.xml
<CustomField>
    <fullName>D__c</fullName>
    <formula>QuestionNumber__r.D__c</formula>
    <label>D</label>
    <type>Text</type>
</CustomField>

Project2/force-app/main/default/objects/Answer__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <formula>QuestionNumber__r.Question__c</formula>
    <label>Question</label>
    <type>Text</type>
</CustomField>

project2/force-app/main/default/objects/Answer__c/fields/Quiz__c.field-meta.xml
<CustomField>
    <fullName>Quiz__c</fullName>
    <formula>QuestionNumber__r.Quiz__r.Name</formula>
    <label>Quiz</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attempt__c/Attempt__c.object-meta.xml
<CustomObject>
    <label>Attempt</label>
    <nameField>
        <displayFormat>AT-{0000}</displayFormat>
        <label>Attempt</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attempts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Attempt__c/fields/Player__c.field-meta.xml
<CustomField>
    <fullName>Player__c</fullName>
    <label>Player</label>
    <referenceTo>Player__c</referenceTo>
    <relationshipLabel>Attempts</relationshipLabel>
    <relationshipName>Attempts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project2/force-app/main/default/objects/Attempt__c/fields/Quiz__c.field-meta.xml
<CustomField>
    <fullName>Quiz__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quiz</label>
    <referenceTo>Quiz__c</referenceTo>
    <relationshipLabel>Attempts</relationshipLabel>
    <relationshipName>Attempts</relationshipName>
    <type>Lookup</type>
</CustomField>

Project2/force-app/main/default/objects/Player__c/Player__c.object-meta.xml
<CustomObject>
    <label>Player</label>
    <nameField>
        <label>Player Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Project2/force-app/main/default/objects/Player__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Players</relationshipName>
    <type>Lookup</type>
</CustomField>

Project2/force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>QuestionNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Project2/force-app/main/default/objects/Question__c/fields/A__c.field-meta.xml
<CustomField>
    <fullName>A__c</fullName>
    <label>A</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <label>Answer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question__c/fields/B__c.field-meta.xml
<CustomField>
    <fullName>B__c</fullName>
    <label>B</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/C__c.field-meta.xml
<CustomField>
    <fullName>C__c</fullName>
    <label>C</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Project2/force-app/main/default/objects/Question__c/fields/D__c.field-meta.xml
<CustomField>
    <fullName>D__c</fullName>
    <label>D</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

project2/force-app/main/default/objects/Question__c/fields/Quiz__c.field-meta.xml
<CustomField>
    <fullName>Quiz__c</fullName>
    <label>Quiz</label>
    <referenceTo>Quiz__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project2/force-app/main/default/objects/Quiz__c/Quiz__c.object-meta.xml
<CustomObject>
    <label>Quiz</label>
    <nameField>
        <label>Quiz Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quizes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Project2/force-app/main/default/objects/Quiz__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>History</fullName>
            </value>
            <value>
                <fullName>Math</fullName>
            </value>
            <value>
                <fullName>Science</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project2/force-app/main/default/classes/QuizPage.cls
public with sharing class QuizPage {
    public string radiovalue {set;get;}
	public Integer rec { get; set; }
    public Integer tot { get; set; }
   	integer totalRecs = 0;
   	integer count= 0;
   	integer LimitSize= 1;
	
    /*
    public PageReference Move()
    {
    PageReference Page = new PageReference('/apex/PlayerPage');
    Page.setRedirect(true);
    return Page;
    }*/
    

	public QuizPage(){
    	tot=totalRecs = [select count() from Question__c];
    }
    
    public List<Quiz__c> Math = [SELECT Id FROM Quiz__c WHERE Category__c = 'Math'];
    public Id playerId=[SELECT Name, User__c FROM PLayer__c WHERE User__c = :UserInfo.getUserID()].Id;
    public Attempt__c attempt = new Attempt__c (Player__c = playerId);
    public Answer__c answer;
    
    
    
    public List<Question__c> questions=new List<Question__c>();
   	public List<Question__c> getQuestions() {
   		List<Question__c> q=[select Name, Question__c, A__c, B__c, C__c, D__c, Quiz__c from Question__c WHERE Quiz__c IN : Math ORDER BY Name LIMIT:limitsize OFFSET:count];
        return q;
    }
    
    public void Submit()
    {
        //implement your logic
    }
    
    public void updatePage() {
        questions.clear();
        limitsize=rec;
        questions=[select Name, Question__c, A__c, B__c, C__c, D__c, Quiz__c from Question__c WHERE Quiz__c IN : Math ORDER BY Name LIMIT:limitsize OFFSET:count];
    }
    
    public PageReference prvbtn() {
    	count=count-limitsize;
        return null;
    }

    public PageReference Nxtbtn() {
 		count=count+limitsize;
        return null;
    }
 
    public Boolean getNxt() {
        if((count+ LimitSize) >= totalRecs)
       		return true;
     	else
       		return false;     
    }
    
    public Boolean getPrv() {
       if(count== 0)
           return true;
       else
           return false;
    }
}