Project2/force-app/main/default/objects/Player__c/Player__c.object-meta.xml
<CustomObject>
    <label>Player</label>
    <nameField>
        <label>Player Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Player__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>place holder of a formula to calculate level and exp base on attempts</description>
    <label>Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Player__c/fields/Quiz_Taken__c.field-meta.xml
<CustomField>
    <fullName>Quiz_Taken__c</fullName>
    <label>Quiz Taken</label>
    <summaryForeignKey>Attempt__c.Player__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Project2/force-app/main/default/objects/Player__c/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <description>place holder for leaderboard rank</description>
    <label>Rank</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Player__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Players</relationshipLabel>
    <relationshipName>Players</relationshipName>
    <type>Lookup</type>
</CustomField>

Project2/force-app/main/default/objects/Player__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Players</relationshipName>
    <type>Lookup</type>
</CustomField>

project2/force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Project2/force-app/main/default/classes/PlayerPage.cls
public with sharing class PlayerPage {

    public PlayerPage(){
    }
    
    public List<Player__c> players=new List<Player__c>();
    public List<Player__c> getplayers() {
        List<Player__c> p=[SELECT Name, User__c, Team__c, Level__c, Rank__c, Quiz_Taken__c 
                           FROM PLayer__c WHERE User__c = :UserInfo.getUserID()];
        return p;
    }
    
    public void updatePage() {
        players.clear();
        players=[SELECT Name, User__c, Team__c, Level__c, Rank__c, Quiz_Taken__c 
                           FROM PLayer__c WHERE User__c = :UserInfo.getUserID()];
    }
}