Project2/force-app/main/default/objects/Player__c/Player__c.object-meta.xml
<CustomObject>
    <label>Player</label>
    <nameField>
        <label>Player Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Player__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Project2/force-app/main/default/objects/Player__c/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <description>place holder for leaderboard rank</description>
    <label>Rank</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Player__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Players</relationshipLabel>
    <relationshipName>Players</relationshipName>
    <type>Lookup</type>
</CustomField>

Project2/force-app/main/default/objects/Player__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Players</relationshipName>
    <type>Lookup</type>
</CustomField>

project2/force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Project2/force-app/main/default/objects/Team__c/fields/Team_Rank__c.field-meta.xml
<CustomField>
    <fullName>Team_Rank__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Team Rank</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/Team_Score__c.field-meta.xml
<CustomField>
    <fullName>Team_Score__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Team Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TeamPage.cls
public class TeamPage {
	public List<Player__c> players { get; set; }
    public Team__c team { get; set; }
    public TeamPage(){
        team = getTeam();
        players = getplayer();
    }
    
    Player__c player =[SELECT Name, User__c, Team__c FROM PLayer__c WHERE User__c = :UserInfo.getUserID() LIMIT 1];
    
    public List<Player__c> getplayer() {
   		List<Player__c> p=[SELECT Name, User__c, Team__c, Points__c, Rank__c FROM PLayer__c WHERE Team__c = :player.Team__c ORDER BY Points__c DESC];
        return p;
    }
    
    public Team__c getTeam() {
        Team__c t=[SELECT Id, Name, Team_Rank__c, Team_Score__c
                           FROM Team__c WHERE Id = :player.Team__c];
        return t;
    } 
}